"""Add attachment model

Revision ID: 20c8efc9bfb8
Revises: 97c6965739f6
Create Date: 2025-04-05 18:46:17.682369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c8efc9bfb8'
down_revision = '97c6965739f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'ERROR', name='teststatus'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('uut_id', sa.String(), nullable=True),
    sa.Column('uut_serial', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_id'), 'test_runs', ['id'], unique=False)
    op.create_index(op.f('ix_test_runs_name'), 'test_runs', ['name'], unique=False)
    op.create_index(op.f('ix_test_runs_uut_id'), 'test_runs', ['uut_id'], unique=False)
    op.create_index(op.f('ix_test_runs_uut_serial'), 'test_runs', ['uut_serial'], unique=False)
    op.create_table('test_phases',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', 'ERROR', name='phasestatus'), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_phases_id'), 'test_phases', ['id'], unique=False)
    op.create_index(op.f('ix_test_phases_name'), 'test_phases', ['name'], unique=False)
    op.create_table('attachments',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('test_run_id', sa.Integer(), nullable=True),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['phase_id'], ['test_phases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_test_phases_name'), table_name='test_phases')
    op.drop_index(op.f('ix_test_phases_id'), table_name='test_phases')
    op.drop_table('test_phases')
    op.drop_index(op.f('ix_test_runs_uut_serial'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_uut_id'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_name'), table_name='test_runs')
    op.drop_index(op.f('ix_test_runs_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ### 