"""Update metadata to meta_data

Revision ID: 97c6965739f6
Revises: 3c5bcc4cf6b3
Create Date: 2025-04-05 14:57:53.466791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c6965739f6'
down_revision = '3c5bcc4cf6b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 